---
# Create symbolic links to ansible executables
- file:
    src: "/opt/csw/bin/{{ item.src }}"
    dest: "/etc/opt/csw/ansible/{{ item.dest }}"
    state: link
  with_items:
    - { src: "ansible", dest: "ansible" }
    - { src: "ansible-playbook", dest: "ansible-playbook" }

# Create playbooks directory
- file:
    path: /etc/opt/csw/ansible/playbooks
    state: directory
    mode: 0755
