---
# oracle environment
oracle_env:
       ORACLE_HOME: "{{ oracle_home }}"
       LD_LIBRARY_PATH: "{{ oracle_home }}"
       TNS_ADMIN: "{{ oracle_home }}"

sql_list_small_tbs_critical: "select * from ({{ sql_list_all_tbs }})
where total < {{ tbs_size_threshold }} and
      used >= {{ small_tbs_usage_alrt_threshold }};"

sql_list_big_tbs_critical: "select * from ({{ sql_list_all_tbs }})
where total >= {{ tbs_size_threshold }} and
      used >= {{ big_tbs_usage_alrt_threshold }};"

sql_list_all_tbs: "select tbs, sum(total) total, sum(free) free, max(maximum) maximum, trunc(((sum(total)-sum(free))/decode(sum(total),0,1,sum(total)))*100,2) used
from (select tablespace_name tbs, sum(bytes)/1024/1024  total, 0 free, 0 maximum
        from dba_data_files
        where tablespace_name not like '%TEMP%'
          and tablespace_name not like '%UNDO%'
          and tablespace_name not like '%_ARC'
          and tablespace_name not like '%_PMDM'
          and tablespace_name not like 'TRDM_200%'
          and tablespace_name not in ('TRDM_2007_D_U32M',        'TRDM_IDX_U256K_PMDM',     'TRDM_U4M_PMDM',
                                      'VISION_MD_2001_U32M_ARC', 'VISION_MD_2002_U32M_ARC', 'VISION_MD_2002_U4M_ARC',
                                      'VISION_MD_2004_U32M_ARC', 'VISION_MD_2004_U4M_ARC',  'VISION_MD_2006_U32M_ARC',
                                      'VISION_MD_2007_U32M_ARC','MINERVA_DATA_DYNAMIC_01','TRDM_2010_D_16K_U32M','TRDM_DATA_2007')
        group by tablespace_name
      UNION ALL
      select tablespace_name tbs, 0 total, sum(bytes)/1024/1024 free, max(bytes)/1024/1024 maximum
        from dba_free_space
        where tablespace_name not like '%TEMP%'
          and tablespace_name not like '%UNDO%'
          and tablespace_name not like '%_ARC'
          and tablespace_name not like '%_PMDM'
          and tablespace_name not like 'TRDM_200%'
          and tablespace_name not in ('TRDM_2007_D_U32M',        'TRDM_IDX_U256K_PMDM',     'TRDM_U4M_PMDM',
                                      'VISION_MD_2001_U32M_ARC', 'VISION_MD_2002_U32M_ARC', 'VISION_MD_2002_U4M_ARC',
                                      'VISION_MD_2004_U32M_ARC', 'VISION_MD_2004_U4M_ARC',  'VISION_MD_2006_U32M_ARC',
                                      'VISION_MD_2007_U32M_ARC','MINERVA_DATA_DYNAMIC_01','TRDM_2010_D_16K_U32M','TRDM_DATA_2007')
        group by tablespace_name)
group by tbs
order by 2 desc"
